#!/usr/bin/env node
/**
 * Image Utilities — sharp-based image processing
 */
import sharp from 'sharp';
import { log } from './logger.js';

/**
 * Resize image
 */
export async function resizeImage(inputPath, outputPath, width, height, options = {}) {
  await sharp(inputPath)
    .resize(width, height, { fit: options.fit || 'cover' })
    .toFile(outputPath);
  log('info', `Resized image: ${outputPath}`);
  return outputPath;
}

/**
 * Enhance image — auto-sharpen, color correction, noise reduction
 */
export async function enhanceImage(inputPath, outputPath, options = {}) {
  let pipeline = sharp(inputPath);

  // Auto-sharpen
  if (options.sharpen !== false) {
    pipeline = pipeline.sharpen({ sigma: options.sharpenSigma || 1.5, flat: 1, jagged: 2 });
  }

  // Color correction (modulate brightness, saturation)
  if (options.colorCorrect !== false) {
    pipeline = pipeline.modulate({
      brightness: options.brightness || 1.05,
      saturation: options.saturation || 1.1,
    });
  }

  // Contrast adjustment
  if (options.contrast) {
    pipeline = pipeline.linear(options.contrast, -(128 * (options.contrast - 1)));
  }

  // Noise reduction (mild blur then sharpen)
  if (options.denoise) {
    pipeline = pipeline.median(options.denoiseRadius || 1);
  }

  await pipeline.toFile(outputPath);
  log('info', `Enhanced image: ${outputPath}`);
  return outputPath;
}

/**
 * Add visible watermark to image
 */
export async function watermarkImage(inputPath, outputPath, text, options = {}) {
  const { fontSize = 48, opacity = 0.6, position = 'southeast' } = options;

  const { createCanvas } = await import('canvas');
  const img = sharp(inputPath);
  const metadata = await img.metadata();

  const canvas = createCanvas(metadata.width, metadata.height);
  const ctx = canvas.getContext('2d');

  // Draw original image
  const originalBuffer = await img.toBuffer();
  const imageData = await sharp(originalBuffer).raw().toBuffer({ resolveWithObject: true });
  // For simplicity, use sharp overlay approach instead

  // Create watermark text as SVG overlay
  const svg = `
    <svg width="${metadata.width}" height="${metadata.height}">
      <style>
        .watermark {
          fill: white;
          font-family: Arial, sans-serif;
          font-size: ${fontSize}px;
          opacity: ${opacity};
          font-weight: bold;
        }
      </style>
      <text x="${metadata.width - 20}" y="${metadata.height - 20}" text-anchor="end" class="watermark">${text}</text>
    </svg>
  `;

  await sharp(inputPath)
    .composite([{ input: Buffer.from(svg), gravity: position }])
    .toFile(outputPath);

  log('info', `Watermarked image: ${outputPath}`);
  return outputPath;
}

/**
 * Add invisible metadata watermark (EXIF / metadata)
 */
export async function addMetadataWatermark(inputPath, outputPath, metadata) {
  const watermarkData = JSON.stringify({
    source: 'Big Starz AI',
    generatedBy: 'big-starz-ai-pipelines',
    watermark: 'AI Generated by Big Starz',
    timestamp: new Date().toISOString(),
    ...metadata,
  });

  await sharp(inputPath)
    .withMetadata({
      exif: {
        IFD0: {
          ImageDescription: watermarkData,
          Copyright: 'AI Generated by Big Starz',
          Artist: 'Big Starz AI Pipeline',
        },
      },
    })
    .toFile(outputPath);

  log('info', `Metadata watermark added: ${outputPath}`);
  return outputPath;
}

/**
 * Convert image buffer to base64 data URI for API calls
 */
export function bufferToDataUri(buffer, mimeType = 'image/png') {
  const base64 = Buffer.from(buffer).toString('base64');
  return `data:${mimeType};base64,${base64}`;
}

/**
 * Load image as buffer from path
 */
export async function loadImageBuffer(inputPath) {
  const fs = await import('fs/promises');
  return fs.readFile(inputPath);
}

/**
 * Get image dimensions
 */
export async function getImageDimensions(inputPath) {
  const metadata = await sharp(inputPath).metadata();
  return { width: metadata.width, height: metadata.height };
}

/**
 * Create a composite image from multiple layers
 */
export async function compositeImage(basePath, overlays, outputPath) {
  const compositeInputs = overlays.map(o => ({
    input: o.path,
    gravity: o.gravity || 'center',
    blend: o.blend || 'over',
    top: o.top,
    left: o.left,
  }));

  await sharp(basePath)
    .composite(compositeInputs)
    .toFile(outputPath);

  log('info', `Composite image saved: ${outputPath}`);
  return outputPath;
}
