#!/usr/bin/env node
/**
 * AI Watermarking Pipeline
 * Adds visible and invisible watermarks to AI-generated content.
 *
 * Usage:
 *   node pipelines/watermark.js <input-file> [watermark-text]
 *
 * Visible watermark: "AI Generated by Big Starz"
 * Invisible watermark: EXIF metadata
 */
import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';
import ffmpeg from 'fluent-ffmpeg';
import {
  getOutputPath,
  generateFilename,
} from '../utils/file-helpers.js';
import { watermarkImage, addMetadataWatermark } from '../utils/image-utils.js';
import { log, error } from '../utils/logger.js';

const DEFAULT_WATERMARK = 'AI Generated by Big Starz';

async function watermarkMedia(inputPath, watermarkText = DEFAULT_WATERMARK) {
  log('info', 'Starting watermarking', { inputPath, watermarkText });

  const ext = path.extname(inputPath).toLowerCase();
  const isVideo = ['.mp4', '.mov', '.avi', '.mkv', '.webm'].includes(ext);
  const isImage = ['.jpg', '.jpeg', '.png', '.webp', '.tiff', '.bmp'].includes(ext);

  if (!isVideo && !isImage) {
    throw new Error(`Unsupported file type: ${ext}`);
  }

  const outputFilename = generateFilename('watermarked', isVideo ? 'mp4' : 'png');
  const outputPath = getOutputPath('watermarked', outputFilename);

  if (isImage) {
    // First add visible watermark, then metadata
    const tempVisible = outputPath + '.tmp.png';
    await watermarkImage(inputPath, tempVisible, watermarkText, {
      fontSize: 48,
      opacity: 0.6,
      position: 'southeast',
    });
    await addMetadataWatermark(tempVisible, outputPath, {
      visibleText: watermarkText,
      source: 'Big Starz AI Pipeline',
    });
    await fs.unlink(tempVisible);
  } else {
    // Video watermarking via ffmpeg drawtext
    await watermarkVideo(inputPath, outputPath, watermarkText);
  }

  // Save metadata
  const metadata = {
    id: outputFilename.replace(/\.(mp4|png)$/, ''),
    timestamp: new Date().toISOString(),
    inputPath,
    outputPath,
    watermarkText,
    type: isVideo ? 'video' : 'image',
    hasVisibleWatermark: true,
    hasMetadataWatermark: true,
  };
  await fs.writeFile(
    getOutputPath('watermarked', outputFilename.replace(/\.(mp4|png)$/, '.json')),
    JSON.stringify(metadata, null, 2)
  );

  log('info', 'Watermarking complete', { outputPath });
  return { outputPath, metadata };
}

function watermarkVideo(inputPath, outputPath, text) {
  return new Promise((resolve, reject) => {
    // Use drawtext filter for visible watermark
    // Fallback to subtitles-style if font not available
    const drawtextFilter = `drawtext=text='${text.replace(/'/g, "'\\\\'")}':` +
      `fontcolor=white@0.6:fontsize=36:` +
      `x=w-tw-20:y=h-th-20:` +
      `box=1:boxcolor=black@0.3:boxborderw=5`;

    ffmpeg(inputPath)
      .videoFilter(drawtextFilter)
      .videoCodec('libx264')
      .audioCodec('copy')
      .outputOptions([
        '-pix_fmt', 'yuv420p',
        '-movflags', '+faststart',
      ])
      .on('start', cmd => log('info', `FFmpeg watermark: ${cmd}`))
      .on('end', () => {
        log('info', `Watermarked video saved: ${outputPath}`);
        resolve(outputPath);
      })
      .on('error', (err) => {
        // Fallback: try without box styling
        log('warn', 'Drawtext failed, trying simpler filter');
        ffmpeg(inputPath)
          .videoFilter(`drawtext=text='${text}':fontcolor=white:fontsize=24:x=10:y=h-th-10`)
          .videoCodec('libx264')
          .audioCodec('copy')
          .outputOptions(['-pix_fmt', 'yuv420p'])
          .on('end', () => resolve(outputPath))
          .on('error', reject)
          .save(outputPath);
      })
      .save(outputPath);
  });
}

// CLI entry point
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const [inputFile, watermarkText = DEFAULT_WATERMARK] = args;

  if (!inputFile) {
    console.log(`
Usage: node pipelines/watermark.js <input-file> [watermark-text]

Example:
  node pipelines/watermark.js ./generated_image.png
  node pipelines/watermark.js ./video.mp4 "AI Generated by Big Starz"
`);
    process.exit(1);
  }

  watermarkMedia(inputFile, watermarkText)
    .then(result => {
      console.log('\n=== WATERMARKING COMPLETE ===');
      console.log(`Output: ${result.outputPath}`);
      console.log(`Visible watermark: "${watermarkText}"`);
      console.log(`Invisible metadata watermark: YES`);
    })
    .catch(err => {
      error('Watermarking failed', { err: err.message });
      process.exit(1);
    });
}

export { watermarkMedia };
